package com.sample;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/sample/User.proto

public final class ProtoUser {
  private ProtoUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required string firstname = 3;
    /**
     * <code>required string firstname = 3;</code>
     */
    boolean hasFirstname();
    /**
     * <code>required string firstname = 3;</code>
     */
    java.lang.String getFirstname();
    /**
     * <code>required string firstname = 3;</code>
     */
    com.google.protobuf.ByteString
        getFirstnameBytes();

    // required string lastname = 4;
    /**
     * <code>required string lastname = 4;</code>
     */
    boolean hasLastname();
    /**
     * <code>required string lastname = 4;</code>
     */
    java.lang.String getLastname();
    /**
     * <code>required string lastname = 4;</code>
     */
    com.google.protobuf.ByteString
        getLastnameBytes();

    // repeated .User.Address addr = 16;
    /**
     * <code>repeated .User.Address addr = 16;</code>
     */
    java.util.List<ProtoUser.User.Address> 
        getAddrList();
    /**
     * <code>repeated .User.Address addr = 16;</code>
     */
    ProtoUser.User.Address getAddr(int index);
    /**
     * <code>repeated .User.Address addr = 16;</code>
     */
    int getAddrCount();
    /**
     * <code>repeated .User.Address addr = 16;</code>
     */
    java.util.List<? extends ProtoUser.User.AddressOrBuilder> 
        getAddrOrBuilderList();
    /**
     * <code>repeated .User.Address addr = 16;</code>
     */
    ProtoUser.User.AddressOrBuilder getAddrOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage
      implements UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private User(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }

    public User getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              firstname_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              lastname_ = input.readBytes();
              break;
            }
            case 130: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                addr_ = new java.util.ArrayList<ProtoUser.User.Address>();
                mutable_bitField0_ |= 0x00000010;
              }
              addr_.add(input.readMessage(ProtoUser.User.Address.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          addr_ = java.util.Collections.unmodifiableList(addr_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoUser.internal_static_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoUser.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoUser.User.class, ProtoUser.User.Builder.class);
    }

    public static com.google.protobuf.Parser<User> PARSER =
        new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public interface AddressOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 id = 1;
      /**
       * <code>required int32 id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required int32 id = 1;</code>
       */
      int getId();

      // required string country = 2 [default = "IND"];
      /**
       * <code>required string country = 2 [default = "IND"];</code>
       */
      boolean hasCountry();
      /**
       * <code>required string country = 2 [default = "IND"];</code>
       */
      java.lang.String getCountry();
      /**
       * <code>required string country = 2 [default = "IND"];</code>
       */
      com.google.protobuf.ByteString
          getCountryBytes();

      // optional string state = 3;
      /**
       * <code>optional string state = 3;</code>
       */
      boolean hasState();
      /**
       * <code>optional string state = 3;</code>
       */
      java.lang.String getState();
      /**
       * <code>optional string state = 3;</code>
       */
      com.google.protobuf.ByteString
          getStateBytes();

      // optional string city = 4;
      /**
       * <code>optional string city = 4;</code>
       */
      boolean hasCity();
      /**
       * <code>optional string city = 4;</code>
       */
      java.lang.String getCity();
      /**
       * <code>optional string city = 4;</code>
       */
      com.google.protobuf.ByteString
          getCityBytes();

      // optional string street = 5;
      /**
       * <code>optional string street = 5;</code>
       */
      boolean hasStreet();
      /**
       * <code>optional string street = 5;</code>
       */
      java.lang.String getStreet();
      /**
       * <code>optional string street = 5;</code>
       */
      com.google.protobuf.ByteString
          getStreetBytes();

      // optional string zip = 6;
      /**
       * <code>optional string zip = 6;</code>
       */
      boolean hasZip();
      /**
       * <code>optional string zip = 6;</code>
       */
      java.lang.String getZip();
      /**
       * <code>optional string zip = 6;</code>
       */
      com.google.protobuf.ByteString
          getZipBytes();

      // optional .User.Address.Type addrType = 7 [default = HOME];
      /**
       * <code>optional .User.Address.Type addrType = 7 [default = HOME];</code>
       */
      boolean hasAddrType();
      /**
       * <code>optional .User.Address.Type addrType = 7 [default = HOME];</code>
       */
      ProtoUser.User.Address.Type getAddrType();
    }
    /**
     * Protobuf type {@code User.Address}
     */
    public static final class Address extends
        com.google.protobuf.GeneratedMessage
        implements AddressOrBuilder {
      // Use Address.newBuilder() to construct.
      private Address(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Address(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Address defaultInstance;
      public static Address getDefaultInstance() {
        return defaultInstance;
      }

      public Address getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Address(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt32();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                country_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                state_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                city_ = input.readBytes();
                break;
              }
              case 42: {
                bitField0_ |= 0x00000010;
                street_ = input.readBytes();
                break;
              }
              case 50: {
                bitField0_ |= 0x00000020;
                zip_ = input.readBytes();
                break;
              }
              case 56: {
                int rawValue = input.readEnum();
                ProtoUser.User.Address.Type value = ProtoUser.User.Address.Type.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(7, rawValue);
                } else {
                  bitField0_ |= 0x00000040;
                  addrType_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoUser.internal_static_User_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoUser.internal_static_User_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoUser.User.Address.class, ProtoUser.User.Address.Builder.class);
      }

      public static com.google.protobuf.Parser<Address> PARSER =
          new com.google.protobuf.AbstractParser<Address>() {
        public Address parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Address> getParserForType() {
        return PARSER;
      }

      /**
       * Protobuf enum {@code User.Address.Type}
       */
      public enum Type
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>HOME = 0;</code>
         */
        HOME(0, 0),
        /**
         * <code>WORK = 1;</code>
         */
        WORK(1, 1),
        /**
         * <code>MOBILE = 2;</code>
         */
        MOBILE(2, 2),
        ;

        /**
         * <code>HOME = 0;</code>
         */
        public static final int HOME_VALUE = 0;
        /**
         * <code>WORK = 1;</code>
         */
        public static final int WORK_VALUE = 1;
        /**
         * <code>MOBILE = 2;</code>
         */
        public static final int MOBILE_VALUE = 2;


        public final int getNumber() { return value; }

        public static Type valueOf(int value) {
          switch (value) {
            case 0: return HOME;
            case 1: return WORK;
            case 2: return MOBILE;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Type>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<Type>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<Type>() {
                public Type findValueByNumber(int number) {
                  return Type.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return ProtoUser.User.Address.getDescriptor().getEnumTypes().get(0);
        }

        private static final Type[] VALUES = values();

        public static Type valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private Type(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:User.Address.Type)
      }

      private int bitField0_;
      // required int32 id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

      // required string country = 2 [default = "IND"];
      public static final int COUNTRY_FIELD_NUMBER = 2;
      private java.lang.Object country_;
      /**
       * <code>required string country = 2 [default = "IND"];</code>
       */
      public boolean hasCountry() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string country = 2 [default = "IND"];</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            country_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string country = 2 [default = "IND"];</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string state = 3;
      public static final int STATE_FIELD_NUMBER = 3;
      private java.lang.Object state_;
      /**
       * <code>optional string state = 3;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string state = 3;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            state_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string state = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string city = 4;
      public static final int CITY_FIELD_NUMBER = 4;
      private java.lang.Object city_;
      /**
       * <code>optional string city = 4;</code>
       */
      public boolean hasCity() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string city = 4;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            city_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string city = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string street = 5;
      public static final int STREET_FIELD_NUMBER = 5;
      private java.lang.Object street_;
      /**
       * <code>optional string street = 5;</code>
       */
      public boolean hasStreet() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string street = 5;</code>
       */
      public java.lang.String getStreet() {
        java.lang.Object ref = street_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            street_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string street = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStreetBytes() {
        java.lang.Object ref = street_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          street_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string zip = 6;
      public static final int ZIP_FIELD_NUMBER = 6;
      private java.lang.Object zip_;
      /**
       * <code>optional string zip = 6;</code>
       */
      public boolean hasZip() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string zip = 6;</code>
       */
      public java.lang.String getZip() {
        java.lang.Object ref = zip_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            zip_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string zip = 6;</code>
       */
      public com.google.protobuf.ByteString
          getZipBytes() {
        java.lang.Object ref = zip_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional .User.Address.Type addrType = 7 [default = HOME];
      public static final int ADDRTYPE_FIELD_NUMBER = 7;
      private ProtoUser.User.Address.Type addrType_;
      /**
       * <code>optional .User.Address.Type addrType = 7 [default = HOME];</code>
       */
      public boolean hasAddrType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .User.Address.Type addrType = 7 [default = HOME];</code>
       */
      public ProtoUser.User.Address.Type getAddrType() {
        return addrType_;
      }

      private void initFields() {
        id_ = 0;
        country_ = "IND";
        state_ = "";
        city_ = "";
        street_ = "";
        zip_ = "";
        addrType_ = ProtoUser.User.Address.Type.HOME;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasCountry()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getCountryBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getStateBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getCityBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeBytes(5, getStreetBytes());
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeBytes(6, getZipBytes());
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeEnum(7, addrType_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getCountryBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getStateBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getCityBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(5, getStreetBytes());
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(6, getZipBytes());
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(7, addrType_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static ProtoUser.User.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoUser.User.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoUser.User.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoUser.User.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoUser.User.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ProtoUser.User.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static ProtoUser.User.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static ProtoUser.User.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static ProtoUser.User.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ProtoUser.User.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ProtoUser.User.Address prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code User.Address}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements ProtoUser.User.AddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProtoUser.internal_static_User_Address_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProtoUser.internal_static_User_Address_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ProtoUser.User.Address.class, ProtoUser.User.Address.Builder.class);
        }

        // Construct using ProtoUser.User.Address.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          country_ = "IND";
          bitField0_ = (bitField0_ & ~0x00000002);
          state_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          city_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          street_ = "";
          bitField0_ = (bitField0_ & ~0x00000010);
          zip_ = "";
          bitField0_ = (bitField0_ & ~0x00000020);
          addrType_ = ProtoUser.User.Address.Type.HOME;
          bitField0_ = (bitField0_ & ~0x00000040);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProtoUser.internal_static_User_Address_descriptor;
        }

        public ProtoUser.User.Address getDefaultInstanceForType() {
          return ProtoUser.User.Address.getDefaultInstance();
        }

        public ProtoUser.User.Address build() {
          ProtoUser.User.Address result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ProtoUser.User.Address buildPartial() {
          ProtoUser.User.Address result = new ProtoUser.User.Address(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.country_ = country_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.state_ = state_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.city_ = city_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.street_ = street_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.zip_ = zip_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.addrType_ = addrType_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ProtoUser.User.Address) {
            return mergeFrom((ProtoUser.User.Address)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ProtoUser.User.Address other) {
          if (other == ProtoUser.User.Address.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasCountry()) {
            bitField0_ |= 0x00000002;
            country_ = other.country_;
            onChanged();
          }
          if (other.hasState()) {
            bitField0_ |= 0x00000004;
            state_ = other.state_;
            onChanged();
          }
          if (other.hasCity()) {
            bitField0_ |= 0x00000008;
            city_ = other.city_;
            onChanged();
          }
          if (other.hasStreet()) {
            bitField0_ |= 0x00000010;
            street_ = other.street_;
            onChanged();
          }
          if (other.hasZip()) {
            bitField0_ |= 0x00000020;
            zip_ = other.zip_;
            onChanged();
          }
          if (other.hasAddrType()) {
            setAddrType(other.getAddrType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasCountry()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ProtoUser.User.Address parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ProtoUser.User.Address) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 id = 1;
        private int id_ ;
        /**
         * <code>required int32 id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public Builder setId(int value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }

        // required string country = 2 [default = "IND"];
        private java.lang.Object country_ = "IND";
        /**
         * <code>required string country = 2 [default = "IND"];</code>
         */
        public boolean hasCountry() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string country = 2 [default = "IND"];</code>
         */
        public java.lang.String getCountry() {
          java.lang.Object ref = country_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            country_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string country = 2 [default = "IND"];</code>
         */
        public com.google.protobuf.ByteString
            getCountryBytes() {
          java.lang.Object ref = country_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            country_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string country = 2 [default = "IND"];</code>
         */
        public Builder setCountry(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          country_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string country = 2 [default = "IND"];</code>
         */
        public Builder clearCountry() {
          bitField0_ = (bitField0_ & ~0x00000002);
          country_ = getDefaultInstance().getCountry();
          onChanged();
          return this;
        }
        /**
         * <code>required string country = 2 [default = "IND"];</code>
         */
        public Builder setCountryBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          country_ = value;
          onChanged();
          return this;
        }

        // optional string state = 3;
        private java.lang.Object state_ = "";
        /**
         * <code>optional string state = 3;</code>
         */
        public boolean hasState() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string state = 3;</code>
         */
        public java.lang.String getState() {
          java.lang.Object ref = state_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            state_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string state = 3;</code>
         */
        public com.google.protobuf.ByteString
            getStateBytes() {
          java.lang.Object ref = state_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            state_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string state = 3;</code>
         */
        public Builder setState(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          state_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string state = 3;</code>
         */
        public Builder clearState() {
          bitField0_ = (bitField0_ & ~0x00000004);
          state_ = getDefaultInstance().getState();
          onChanged();
          return this;
        }
        /**
         * <code>optional string state = 3;</code>
         */
        public Builder setStateBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          state_ = value;
          onChanged();
          return this;
        }

        // optional string city = 4;
        private java.lang.Object city_ = "";
        /**
         * <code>optional string city = 4;</code>
         */
        public boolean hasCity() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional string city = 4;</code>
         */
        public java.lang.String getCity() {
          java.lang.Object ref = city_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            city_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string city = 4;</code>
         */
        public com.google.protobuf.ByteString
            getCityBytes() {
          java.lang.Object ref = city_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            city_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string city = 4;</code>
         */
        public Builder setCity(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          city_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string city = 4;</code>
         */
        public Builder clearCity() {
          bitField0_ = (bitField0_ & ~0x00000008);
          city_ = getDefaultInstance().getCity();
          onChanged();
          return this;
        }
        /**
         * <code>optional string city = 4;</code>
         */
        public Builder setCityBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          city_ = value;
          onChanged();
          return this;
        }

        // optional string street = 5;
        private java.lang.Object street_ = "";
        /**
         * <code>optional string street = 5;</code>
         */
        public boolean hasStreet() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional string street = 5;</code>
         */
        public java.lang.String getStreet() {
          java.lang.Object ref = street_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            street_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string street = 5;</code>
         */
        public com.google.protobuf.ByteString
            getStreetBytes() {
          java.lang.Object ref = street_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            street_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string street = 5;</code>
         */
        public Builder setStreet(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
          street_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string street = 5;</code>
         */
        public Builder clearStreet() {
          bitField0_ = (bitField0_ & ~0x00000010);
          street_ = getDefaultInstance().getStreet();
          onChanged();
          return this;
        }
        /**
         * <code>optional string street = 5;</code>
         */
        public Builder setStreetBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
          street_ = value;
          onChanged();
          return this;
        }

        // optional string zip = 6;
        private java.lang.Object zip_ = "";
        /**
         * <code>optional string zip = 6;</code>
         */
        public boolean hasZip() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional string zip = 6;</code>
         */
        public java.lang.String getZip() {
          java.lang.Object ref = zip_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            zip_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string zip = 6;</code>
         */
        public com.google.protobuf.ByteString
            getZipBytes() {
          java.lang.Object ref = zip_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            zip_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string zip = 6;</code>
         */
        public Builder setZip(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
          zip_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string zip = 6;</code>
         */
        public Builder clearZip() {
          bitField0_ = (bitField0_ & ~0x00000020);
          zip_ = getDefaultInstance().getZip();
          onChanged();
          return this;
        }
        /**
         * <code>optional string zip = 6;</code>
         */
        public Builder setZipBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
          zip_ = value;
          onChanged();
          return this;
        }

        // optional .User.Address.Type addrType = 7 [default = HOME];
        private ProtoUser.User.Address.Type addrType_ = ProtoUser.User.Address.Type.HOME;
        /**
         * <code>optional .User.Address.Type addrType = 7 [default = HOME];</code>
         */
        public boolean hasAddrType() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional .User.Address.Type addrType = 7 [default = HOME];</code>
         */
        public ProtoUser.User.Address.Type getAddrType() {
          return addrType_;
        }
        /**
         * <code>optional .User.Address.Type addrType = 7 [default = HOME];</code>
         */
        public Builder setAddrType(ProtoUser.User.Address.Type value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000040;
          addrType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .User.Address.Type addrType = 7 [default = HOME];</code>
         */
        public Builder clearAddrType() {
          bitField0_ = (bitField0_ & ~0x00000040);
          addrType_ = ProtoUser.User.Address.Type.HOME;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:User.Address)
      }

      static {
        defaultInstance = new Address(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:User.Address)
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string firstname = 3;
    public static final int FIRSTNAME_FIELD_NUMBER = 3;
    private java.lang.Object firstname_;
    /**
     * <code>required string firstname = 3;</code>
     */
    public boolean hasFirstname() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string firstname = 3;</code>
     */
    public java.lang.String getFirstname() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string firstname = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFirstnameBytes() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string lastname = 4;
    public static final int LASTNAME_FIELD_NUMBER = 4;
    private java.lang.Object lastname_;
    /**
     * <code>required string lastname = 4;</code>
     */
    public boolean hasLastname() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string lastname = 4;</code>
     */
    public java.lang.String getLastname() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string lastname = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLastnameBytes() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .User.Address addr = 16;
    public static final int ADDR_FIELD_NUMBER = 16;
    private java.util.List<ProtoUser.User.Address> addr_;
    /**
     * <code>repeated .User.Address addr = 16;</code>
     */
    public java.util.List<ProtoUser.User.Address> getAddrList() {
      return addr_;
    }
    /**
     * <code>repeated .User.Address addr = 16;</code>
     */
    public java.util.List<? extends ProtoUser.User.AddressOrBuilder> 
        getAddrOrBuilderList() {
      return addr_;
    }
    /**
     * <code>repeated .User.Address addr = 16;</code>
     */
    public int getAddrCount() {
      return addr_.size();
    }
    /**
     * <code>repeated .User.Address addr = 16;</code>
     */
    public ProtoUser.User.Address getAddr(int index) {
      return addr_.get(index);
    }
    /**
     * <code>repeated .User.Address addr = 16;</code>
     */
    public ProtoUser.User.AddressOrBuilder getAddrOrBuilder(
        int index) {
      return addr_.get(index);
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      firstname_ = "";
      lastname_ = "";
      addr_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFirstname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAddrCount(); i++) {
        if (!getAddr(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFirstnameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getLastnameBytes());
      }
      for (int i = 0; i < addr_.size(); i++) {
        output.writeMessage(16, addr_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFirstnameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getLastnameBytes());
      }
      for (int i = 0; i < addr_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, addr_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtoUser.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoUser.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoUser.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoUser.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoUser.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoUser.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoUser.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoUser.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoUser.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoUser.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoUser.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoUser.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoUser.internal_static_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoUser.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoUser.User.class, ProtoUser.User.Builder.class);
      }

      // Construct using ProtoUser.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAddrFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        firstname_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        lastname_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (addrBuilder_ == null) {
          addr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          addrBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoUser.internal_static_User_descriptor;
      }

      public ProtoUser.User getDefaultInstanceForType() {
        return ProtoUser.User.getDefaultInstance();
      }

      public ProtoUser.User build() {
        ProtoUser.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoUser.User buildPartial() {
        ProtoUser.User result = new ProtoUser.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.firstname_ = firstname_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lastname_ = lastname_;
        if (addrBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            addr_ = java.util.Collections.unmodifiableList(addr_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.addr_ = addr_;
        } else {
          result.addr_ = addrBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoUser.User) {
          return mergeFrom((ProtoUser.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoUser.User other) {
        if (other == ProtoUser.User.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasFirstname()) {
          bitField0_ |= 0x00000004;
          firstname_ = other.firstname_;
          onChanged();
        }
        if (other.hasLastname()) {
          bitField0_ |= 0x00000008;
          lastname_ = other.lastname_;
          onChanged();
        }
        if (addrBuilder_ == null) {
          if (!other.addr_.isEmpty()) {
            if (addr_.isEmpty()) {
              addr_ = other.addr_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureAddrIsMutable();
              addr_.addAll(other.addr_);
            }
            onChanged();
          }
        } else {
          if (!other.addr_.isEmpty()) {
            if (addrBuilder_.isEmpty()) {
              addrBuilder_.dispose();
              addrBuilder_ = null;
              addr_ = other.addr_;
              bitField0_ = (bitField0_ & ~0x00000010);
              addrBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAddrFieldBuilder() : null;
            } else {
              addrBuilder_.addAllMessages(other.addr_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasFirstname()) {
          
          return false;
        }
        if (!hasLastname()) {
          
          return false;
        }
        for (int i = 0; i < getAddrCount(); i++) {
          if (!getAddr(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoUser.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoUser.User) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // required string firstname = 3;
      private java.lang.Object firstname_ = "";
      /**
       * <code>required string firstname = 3;</code>
       */
      public boolean hasFirstname() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string firstname = 3;</code>
       */
      public java.lang.String getFirstname() {
        java.lang.Object ref = firstname_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          firstname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string firstname = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFirstnameBytes() {
        java.lang.Object ref = firstname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string firstname = 3;</code>
       */
      public Builder setFirstname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        firstname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string firstname = 3;</code>
       */
      public Builder clearFirstname() {
        bitField0_ = (bitField0_ & ~0x00000004);
        firstname_ = getDefaultInstance().getFirstname();
        onChanged();
        return this;
      }
      /**
       * <code>required string firstname = 3;</code>
       */
      public Builder setFirstnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        firstname_ = value;
        onChanged();
        return this;
      }

      // required string lastname = 4;
      private java.lang.Object lastname_ = "";
      /**
       * <code>required string lastname = 4;</code>
       */
      public boolean hasLastname() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string lastname = 4;</code>
       */
      public java.lang.String getLastname() {
        java.lang.Object ref = lastname_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          lastname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string lastname = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLastnameBytes() {
        java.lang.Object ref = lastname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string lastname = 4;</code>
       */
      public Builder setLastname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        lastname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string lastname = 4;</code>
       */
      public Builder clearLastname() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastname_ = getDefaultInstance().getLastname();
        onChanged();
        return this;
      }
      /**
       * <code>required string lastname = 4;</code>
       */
      public Builder setLastnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        lastname_ = value;
        onChanged();
        return this;
      }

      // repeated .User.Address addr = 16;
      private java.util.List<ProtoUser.User.Address> addr_ =
        java.util.Collections.emptyList();
      private void ensureAddrIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          addr_ = new java.util.ArrayList<ProtoUser.User.Address>(addr_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoUser.User.Address, ProtoUser.User.Address.Builder, ProtoUser.User.AddressOrBuilder> addrBuilder_;

      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public java.util.List<ProtoUser.User.Address> getAddrList() {
        if (addrBuilder_ == null) {
          return java.util.Collections.unmodifiableList(addr_);
        } else {
          return addrBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public int getAddrCount() {
        if (addrBuilder_ == null) {
          return addr_.size();
        } else {
          return addrBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public ProtoUser.User.Address getAddr(int index) {
        if (addrBuilder_ == null) {
          return addr_.get(index);
        } else {
          return addrBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public Builder setAddr(
          int index, ProtoUser.User.Address value) {
        if (addrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddrIsMutable();
          addr_.set(index, value);
          onChanged();
        } else {
          addrBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public Builder setAddr(
          int index, ProtoUser.User.Address.Builder builderForValue) {
        if (addrBuilder_ == null) {
          ensureAddrIsMutable();
          addr_.set(index, builderForValue.build());
          onChanged();
        } else {
          addrBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public Builder addAddr(ProtoUser.User.Address value) {
        if (addrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddrIsMutable();
          addr_.add(value);
          onChanged();
        } else {
          addrBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public Builder addAddr(
          int index, ProtoUser.User.Address value) {
        if (addrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddrIsMutable();
          addr_.add(index, value);
          onChanged();
        } else {
          addrBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public Builder addAddr(
          ProtoUser.User.Address.Builder builderForValue) {
        if (addrBuilder_ == null) {
          ensureAddrIsMutable();
          addr_.add(builderForValue.build());
          onChanged();
        } else {
          addrBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public Builder addAddr(
          int index, ProtoUser.User.Address.Builder builderForValue) {
        if (addrBuilder_ == null) {
          ensureAddrIsMutable();
          addr_.add(index, builderForValue.build());
          onChanged();
        } else {
          addrBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public Builder addAllAddr(
          java.lang.Iterable<? extends ProtoUser.User.Address> values) {
        if (addrBuilder_ == null) {
          ensureAddrIsMutable();
          super.addAll(values, addr_);
          onChanged();
        } else {
          addrBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public Builder clearAddr() {
        if (addrBuilder_ == null) {
          addr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          addrBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public Builder removeAddr(int index) {
        if (addrBuilder_ == null) {
          ensureAddrIsMutable();
          addr_.remove(index);
          onChanged();
        } else {
          addrBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public ProtoUser.User.Address.Builder getAddrBuilder(
          int index) {
        return getAddrFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public ProtoUser.User.AddressOrBuilder getAddrOrBuilder(
          int index) {
        if (addrBuilder_ == null) {
          return addr_.get(index);  } else {
          return addrBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public java.util.List<? extends ProtoUser.User.AddressOrBuilder> 
           getAddrOrBuilderList() {
        if (addrBuilder_ != null) {
          return addrBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(addr_);
        }
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public ProtoUser.User.Address.Builder addAddrBuilder() {
        return getAddrFieldBuilder().addBuilder(
            ProtoUser.User.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public ProtoUser.User.Address.Builder addAddrBuilder(
          int index) {
        return getAddrFieldBuilder().addBuilder(
            index, ProtoUser.User.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .User.Address addr = 16;</code>
       */
      public java.util.List<ProtoUser.User.Address.Builder> 
           getAddrBuilderList() {
        return getAddrFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ProtoUser.User.Address, ProtoUser.User.Address.Builder, ProtoUser.User.AddressOrBuilder> 
          getAddrFieldBuilder() {
        if (addrBuilder_ == null) {
          addrBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ProtoUser.User.Address, ProtoUser.User.Address.Builder, ProtoUser.User.AddressOrBuilder>(
                  addr_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          addr_ = null;
        }
        return addrBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:User)
    }

    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:User)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_User_Address_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_User_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#src/main/java/com/sample/User.proto\"\236\002" +
      "\n\004User\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\021\n\tfirs" +
      "tname\030\003 \002(\t\022\020\n\010lastname\030\004 \002(\t\022\033\n\004addr\030\020 " +
      "\003(\0132\r.User.Address\032\271\001\n\007Address\022\n\n\002id\030\001 \002" +
      "(\005\022\024\n\007country\030\002 \002(\t:\003IND\022\r\n\005state\030\003 \001(\t\022" +
      "\014\n\004city\030\004 \001(\t\022\016\n\006street\030\005 \001(\t\022\013\n\003zip\030\006 \001" +
      "(\t\022*\n\010addrType\030\007 \001(\0162\022.User.Address.Type" +
      ":\004HOME\"&\n\004Type\022\010\n\004HOME\020\000\022\010\n\004WORK\020\001\022\n\n\006MO" +
      "BILE\020\002B\013B\tProtoUser"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_User_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_User_descriptor,
              new java.lang.String[] { "Id", "Name", "Firstname", "Lastname", "Addr", });
          internal_static_User_Address_descriptor =
            internal_static_User_descriptor.getNestedTypes().get(0);
          internal_static_User_Address_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_User_Address_descriptor,
              new java.lang.String[] { "Id", "Country", "State", "City", "Street", "Zip", "AddrType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
